# Automatically generated by /home/ubuntu/buildroot/support/scripts/mkmakefile: don't edit
# Oh but I did edit it. Whatcha gonna do?
lastword = $(word $(words $(1)),$(1))
makedir := $(dir $(call lastword,$(MAKEFILE_LIST)))

MAKEARGS := -C ~/src/buildroot O=$(CURDIR)/build BR2_CONFIG=$(CURDIR)/buildroot.config
# MAKEARGS += O=$(if $(patsubst /%,,$(makedir)),$(CURDIR)/)$(patsubst %/,%,$(makedir))

MAKEFLAGS += --no-print-directory

.PHONY: _all $(MAKECMDGOALS)

all	:= $(filter-out Makefile,$(MAKECMDGOALS))

_all:
	umask 0022 && $(MAKE) $(MAKEARGS) $(all)

Makefile:;

$(all): _all
	@:

%/: _all
	@:
